# Node IDL

Interface documentation generation for Node.js JavaScript and CoffeeScript.

## Synopsis

Node IDL helps you generate a nice landing page for the GitHub Pages of your
Node.js modules. Node IDL supports both JavaScript and CoffeeScript.

Once you've written an `*.idl` file for your project, you can run it through
the `node-idl` translator to generate multi-section, scrollable landing page, a
man page, or a  `*.markdown` page, so that the same documentation can be found
where ever the user turns for answers.

Node IDL is meant for utility programs, and it man page sized in scope. If you
have a complicated framework, your documentation needs may be to greate for Node
IDL, but if you're a programmer who just spiked an awesome new module, and you
want to have your house in order when you announce, Node IDL is the markup
langauge for you.

```
# Project Name

A one liner describing the project.

## Synopsis

Write something to hook them.

## Installing

Make it quick.

## Guide

Reel them in.

## Reference

namespace:  ftp

Describe your namespace.

function:   createClient

  parameter:  host

  Indentation is used to group the parameter documentation to the parameter.

Explain the use of this function.

class:      FTPClient

  factory:    ftp.createClient

  Describe how to create the class using a factory.

Describe the use of this class.

  event: data

    parameter: chunk

    This is a parameter given to the callback.

  Explain the use of this event.

```

## Rationale

CoffeeScript already has an excellend documentation tool named
[Docco](http://jashkenas.github.com/docco/) that generated literate programming
style documetation. The documentation is taken from the source file and
presented in a two column format, so that the syntax highlighted source code is
side-by-side with its line documentation.

The annotated source code format is beautiful. It clearly describes the purpose
of the code. It makes it easy to learn CoffeeScript to read the source of
existing CoffeeScript programs.

This is different from other documentation tools like **RDoc** or **Javadoc**,
which hide the source code in accordance with the "design by contact" and
"program to interfaces" tenants of the bureaucratic software development.

Those programmers, and there are many, who interpret the happenstance of their
software environment as meaningful stricture, tend to see the API style of
annotating functions as some form of Good Thing, and that showing source code in
thier documentation is a Bad Thing. Because they can't do it, it must be that
they is is bad to do it. It is a just world after all.

The literate programming nature of Docco and CoffeeScript is something
different, something good. This documents the implementation and focuses that
documentation on the source. It makes it easy to learn CoffeeScript, just read
the annotated source of the CoffeeScript programmers who inspire you.

But, documenting the API is important too. Users who are JavaScript programmers
and uninterested in CoffeeScript will be interested only in how to use a library
and will not want to see the sausage being made.

### Embedded API Documentation is A Bridge Too Far

I greatly appreciate Docco as a means to document the source code itself, and
would **hate** to see that polluted with API documentation.

Adding embedded API would overload Docco. Although there are [some lovely
examples of Docco that explain implementation *and*
interface](http://sstephenson.github.com/strscan-js/), when you want to include
source code examples, detailed descriptions of parameters or callback
parameters, or show the API outline, the Docco can become disproportionately
documentation.

In fact, the bulk of programming is not an API. The bulk of of programming is
applications, and documenting applications in that pseudo-formal, "pay no
attention to the man behind the curtain" style of documentation is needlessly
bureaucratic. You might have the URL to handler bindings for your application
defined using domain-specific langauge, right there, three lines below a tedious
repetition of what would be obvious if only you could see the source.

The API style of documentation adds a lot of work, but little value, if the
software is not supposed to be a black box, but a living application. The Docco
style is a good fit, turning the software into its own story.

Which is why Node IDL aspires to give the developer a nice superset of Markdown
to desrcribe their program outside of their program.

### But, External Documentation Will Get Out of Sync

No more so than embedded API documentation. API documentation is no fun to
write. Even when it is snuggled up to the code that implements it, it falls out
of sync with the implementation. It falls out of sync because it is painful to
try to describe software without code to illustrate the software.

Docco stays in sync because the illustrative code is the actual code. It stays
in sync because Docco is beautiful and because generating meaningful Docco
generates a sense of accomplishment.

Node IDL will be accurate because it will generate project documentation that is
structured, meaningiful, and beautiful. It will generate project documentation
in today's fashion of the succinct scrollable project page. Node IDL will be
accurate because there will be real benefit to keeping it accurate.

## Reference

namespace: idl

Node ILD exports methods through its idl namespace.

```javascript
var idl = require("idl");
```
function:   generate

  parameter:  source 

  The source IDL file to parse.

  parameter:  destination

  The output file to generate.

Generates an HTML page from the IDL `source` and emits the HTML in the
`destination` file. The method is asynchronous.
